<?php

use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

// Determine if the application is in maintenance mode...
if (file_exists($maintenance = __DIR__.'/../storage/framework/maintenance.php')) {
    require $maintenance;
}

// Ensure storage directories always exist before Laravel boots.
// On a fresh clone (Plesk, git clone) these directories are absent and
// Laravel's Compiler will throw "Please provide a valid cache path".
foreach ([
    '/storage/framework/cache/data',
    '/storage/framework/sessions',
    '/storage/framework/views',
    '/storage/logs',
    '/storage/app/private',
    '/storage/app/public',
    '/bootstrap/cache',
] as $dir) {
    $path = __DIR__.'/..'.$dir;
    if (! is_dir($path)) {
        @mkdir($path, 0775, true);
    }
}

// Register the Composer autoloader...
$autoload = __DIR__.'/../vendor/autoload.php';
if (! is_file($autoload)) {
    // The vendor directory is generated by Composer and must never be created
    // manually. Show a clear error instead of a PHP fatal error.
    http_response_code(500);
    header('Content-Type: text/html; charset=UTF-8');
    echo <<<'HTML'
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Dépendances non installées · KelvCMC</title>
<style>
    * { box-sizing: border-box; }
    body { margin: 0; min-height: 100vh; display: grid; place-items: center; padding: 2rem; background: #0b1120; color: #e2e8f0; font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }
    .card { width: 100%; max-width: 640px; padding: 2.5rem; background: #0f172a; border: 1px solid #1e293b; border-radius: 1rem; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, .5); }
    .badge { display: inline-block; padding: .25rem .625rem; border-radius: 9999px; background: rgba(139, 92, 246, .15); border: 1px solid rgba(139, 92, 246, .35); color: #c4b5fd; font-size: .75rem; font-weight: 600; letter-spacing: .05em; text-transform: uppercase; }
    h1 { margin: 1.25rem 0 .5rem; font-size: 1.5rem; line-height: 1.25; }
    p { margin: 0 0 1rem; line-height: 1.6; color: #94a3b8; }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: .875rem; color: #c4b5fd; }
    pre { margin: 1rem 0; padding: .875rem 1.125rem; overflow-x: auto; background: #1e293b; border: 1px solid #334155; border-radius: .5rem; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: .875rem; color: #e9d5ff; user-select: all; }
    a { color: #a78bfa; text-decoration: none; }
    a:hover { text-decoration: underline; }
</style>
</head>
<body>
<main class="card">
    <span class="badge">Erreur 500</span>
    <h1>Dépendances PHP non installées</h1>
    <p>Le fichier <code>vendor/autoload.php</code> est introuvable. Le dossier <code>vendor</code> est généré automatiquement par Composer et ne doit jamais être créé à la main.</p>
    <p>Depuis la racine du projet, exécutez :</p>
    <pre>composer install</pre>
    <p>Puis rechargez cette page. Consultez <a href="https://getcomposer.org/doc/00-intro.md">la documentation Composer</a> si Composer n&rsquo;est pas encore installé.</p>
</main>
</body>
</html>
HTML;
    exit(1);
}
require $autoload;

// Prepare a fresh checkout for the web installer before Laravel boots. The
// installer must be able to start without an existing .env, APP_KEY or DB.
$environmentFile = __DIR__.'/../.env';
$createdEnvironment = false;
if (! is_file($environmentFile) && is_file(__DIR__.'/../.env.example')) {
    copy(__DIR__.'/../.env.example', $environmentFile);
    $createdEnvironment = true;
}

$environment = is_file($environmentFile) ? (string) file_get_contents($environmentFile) : '';
if (! is_file(__DIR__.'/../storage/installed.lock')) {
    // Ensure .env ends with a newline before appending values.
    $environment = rtrim($environment).PHP_EOL;

    if (! preg_match('/^KELVCMC_INSTALLER_ORIGINAL_SESSION_DRIVER=/m', $environment)
        && preg_match('/^SESSION_DRIVER=(.*)$/m', $environment, $sessionMatch)) {
        $environment .= 'KELVCMC_INSTALLER_ORIGINAL_SESSION_DRIVER='.$sessionMatch[1].PHP_EOL;
    }
    if (! preg_match('/^KELVCMC_INSTALLER_ORIGINAL_CACHE_STORE=/m', $environment)
        && preg_match('/^CACHE_STORE=(.*)$/m', $environment, $cacheMatch)) {
        $environment .= 'KELVCMC_INSTALLER_ORIGINAL_CACHE_STORE='.$cacheMatch[1].PHP_EOL;
    }

    if (preg_match('/^SESSION_DRIVER=.*$/m', $environment)) {
        $environment = (string) preg_replace('/^SESSION_DRIVER=.*$/m', 'SESSION_DRIVER=file', $environment);
    } else {
        $environment .= 'SESSION_DRIVER=file'.PHP_EOL;
    }
    if (preg_match('/^CACHE_STORE=.*$/m', $environment)) {
        $environment = (string) preg_replace('/^CACHE_STORE=.*$/m', 'CACHE_STORE=file', $environment);
    } else {
        $environment .= 'CACHE_STORE=file'.PHP_EOL;
    }
    file_put_contents($environmentFile, $environment, LOCK_EX);
}

// Laravel's session middleware requires APP_KEY. The web installer can still
// start on a fresh checkout by creating a temporary key in .env; it will be
// replaced only when no key exists.
if (is_file($environmentFile) && ! preg_match('/^APP_KEY=.+$/m', (string) file_get_contents($environmentFile))) {
    $key = 'base64:'.base64_encode(random_bytes(32));
    $contents = (string) file_get_contents($environmentFile);
    $contents = preg_replace('/^APP_KEY=.*$/m', 'APP_KEY='.$key, $contents, 1, $count);
    if ($count === 0) {
        $contents = rtrim($contents).PHP_EOL.'APP_KEY='.$key.PHP_EOL;
    }
    file_put_contents($environmentFile, $contents, LOCK_EX);
}

// Bootstrap Laravel and handle the request...
(require_once __DIR__.'/../bootstrap/app.php')
    ->handleRequest(Request::capture());
